version: '3'

services:
  web:
    build: .
    container_name: php_apache_server
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/apache2
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydb

  db:
    image: mysql:8.0
    container_name: mysql_server
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: user
      MYSQL_USER: password
      MYSQL_PASSWORD: mydb
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
